/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StButton {
    }
    interface StComp {
    }
    interface StHero {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStButtonElement extends Components.StButton, HTMLStencilElement {
    }
    var HTMLStButtonElement: {
        prototype: HTMLStButtonElement;
        new (): HTMLStButtonElement;
    };
    interface HTMLStCompElement extends Components.StComp, HTMLStencilElement {
    }
    var HTMLStCompElement: {
        prototype: HTMLStCompElement;
        new (): HTMLStCompElement;
    };
    interface HTMLStHeroElement extends Components.StHero, HTMLStencilElement {
    }
    var HTMLStHeroElement: {
        prototype: HTMLStHeroElement;
        new (): HTMLStHeroElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "st-button": HTMLStButtonElement;
        "st-comp": HTMLStCompElement;
        "st-hero": HTMLStHeroElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StButton {
    }
    interface StComp {
    }
    interface StHero {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "st-button": StButton;
        "st-comp": StComp;
        "st-hero": StHero;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "st-button": LocalJSX.StButton & JSXBase.HTMLAttributes<HTMLStButtonElement>;
            "st-comp": LocalJSX.StComp & JSXBase.HTMLAttributes<HTMLStCompElement>;
            "st-hero": LocalJSX.StHero & JSXBase.HTMLAttributes<HTMLStHeroElement>;
        }
    }
}
